### ISSUE TITLE
Pages: System Map

### ISSUE THREAD

**Issue by LodenH16** [Multiplied-By-One/MBO-App#7]
This Issue will be dependent on the following issues:
- [ ] #8  HeadMates Listing page
- [ ] #9  HeadMates Creation form
- [ ] #10 HeadMate Profile page
---
> *taken from the grand pdf, [page 8](https://drive.google.com/file/d/1JGqPSo2Lem2A_XrcSU9h19yzHA19k7Ba/view?usp=sharing)*

The System Map profile that is accessed after the basic profile input has additional traits and information that can then be added.
The basic name, gender, age, and profile pic are added, then that appears on the System Map as a clickable button that leads to the associated profile

Traits and prompts from the dropdown could be filtered alphabetically.

After the trait or prompt is added, it can then have a fill space where additional information related to it can be input. This is editable afterward.

The space where traits are input is scrollable.

Each trait is distinguished from the input text by being bold and larger. Each trait has a one-point line around the text.

The list of traits that can be added will have explanations as to their definitions within the terms in the Guide, which can also be accessed by clicking the question mark next to the trait bar options menu.

Only the traits and prompts are listed in the traits bar; not their definitions.

The ellipsis at the top offer the options to:

- Delete Profile (Warning that this would disconnect the associated Eye
account.) (If that account has a password, it will need to be entered)

- Edit basic profile (This takes you to what looks like the basic profile
setup, but would be labeled to “Change basic profile”)

- Select added traits (This offers to select traits to delete specific ones)
- 
![image](https://user-images.githubusercontent.com/68450309/191644567-22803e50-db22-4582-9ab9-528521d2f8f4.png)

![image](https://user-images.githubusercontent.com/68450309/191644597-15dde46d-e8e0-45e4-bdc3-4650a6ea6dc2.png)

![image](https://user-images.githubusercontent.com/68450309/191644609-6e2c8861-288e-442a-9d68-6879e99a57dd.png)

![image](https://user-images.githubusercontent.com/68450309/191644624-1343fd94-1a1c-4d73-bb86-735499b72cbd.png)
